/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiónpedidos;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Frans
 */
public class GestionPedidos extends javax.swing.JFrame {

    static javax.swing.JFrame Principal;
    private Vector vArticulos = new Vector();
    String op="";
    public Statement st;
    GestorBD bd = new GestorBD();
    
    
    /**
     * Creates new form GestionPedidos
     */
    public GestionPedidos(javax.swing.JFrame padre) {
            GestionPedidos.Principal=padre;
            initComponents();
            enableEvents(java.awt.AWTEvent.WINDOW_EVENT_MASK);
            this.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
            
            setTitle("Gestión de Almacén - Pedidos");
        try {
            bd.conectarDB();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "ERROR AL CONECTAR.");
        } 
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldNif = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDom = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldLoc = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldArt = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldDesc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldUnid = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldImp = new javax.swing.JTextField();
        jButtonFactura = new javax.swing.JButton();
        jButtonAcept = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jButtonCancelPed = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jScrollPaneArticulos = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBarArticulos = new javax.swing.JScrollBar();
        jButtonGrid = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPedidos = new javax.swing.JMenu();
        jMenuItemClientes = new javax.swing.JMenuItem();
        jMenuItemProve = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemReturn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Almacén - Pedidos");

        jLabel1.setText("Código");

        jLabel2.setText("N.I.F.");

        jLabel3.setText("Nombre");

        jTextFieldCod.setEnabled(false);
        jTextFieldCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodKeyPressed(evt);
            }
        });

        jTextFieldNif.setEnabled(false);

        jTextFieldNombre.setEnabled(false);

        jTextFieldApe.setEnabled(false);

        jLabel4.setText("Apellidos");

        jLabel5.setText("Domicilio");

        jTextFieldDom.setEnabled(false);

        jLabel6.setText("Código Postal");

        jTextFieldCp.setEnabled(false);

        jLabel7.setText("Localidad");

        jTextFieldLoc.setEnabled(false);

        jLabel8.setText("Total");

        jTextFieldTotal.setEnabled(false);

        jLabel9.setText("--------------------------------------------------------------------------------------------------------------");

        jLabel10.setText("Artículo");

        jTextFieldArt.setEnabled(false);

        jLabel11.setText("Descripción");

        jTextFieldDesc.setEnabled(false);

        jLabel12.setText("Unidades");

        jTextFieldUnid.setEnabled(false);

        jLabel13.setText("Stock");

        jTextFieldStock.setEnabled(false);

        jLabel14.setText("Precio");

        jTextFieldPrecio.setEnabled(false);

        jLabel15.setText("Importe");

        jTextFieldImp.setEnabled(false);

        jButtonFactura.setMnemonic('f');
        jButtonFactura.setText("Factura");
        jButtonFactura.setEnabled(false);

        jButtonAcept.setMnemonic('a');
        jButtonAcept.setText("Aceptar");
        jButtonAcept.setEnabled(false);

        jButtonExit.setMnemonic('s');
        jButtonExit.setText("Salir");
        jButtonExit.setEnabled(false);

        jButtonCancelPed.setMnemonic('p');
        jButtonCancelPed.setText("Cancelar Pedido");
        jButtonCancelPed.setEnabled(false);

        jButtonCancel.setMnemonic('c');
        jButtonCancel.setText("Cancelar Todo");
        jButtonCancel.setEnabled(false);

        jScrollPaneArticulos.setHorizontalScrollBar(jScrollBarArticulos);
        jScrollPaneArticulos.setVerticalScrollBar(jScrollBarArticulos);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPaneArticulos.setViewportView(jTable1);

        jButtonGrid.setText("...");
        jButtonGrid.setEnabled(false);
        jButtonGrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGridActionPerformed(evt);
            }
        });

        jMenuPedidos.setMnemonic('p');
        jMenuPedidos.setText("Pedidos");

        jMenuItemClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemClientes.setMnemonic('c');
        jMenuItemClientes.setText("Clientes");
        jMenuItemClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClientesActionPerformed(evt);
            }
        });
        jMenuPedidos.add(jMenuItemClientes);

        jMenuItemProve.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemProve.setMnemonic('p');
        jMenuItemProve.setText("Proveedores");
        jMenuItemProve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProveActionPerformed(evt);
            }
        });
        jMenuPedidos.add(jMenuItemProve);
        jMenuPedidos.add(jSeparator1);

        jMenuItemReturn.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemReturn.setMnemonic('v');
        jMenuItemReturn.setText("Volver");
        jMenuPedidos.add(jMenuItemReturn);

        jMenuBar1.add(jMenuPedidos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(jButtonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonAcept, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jTextFieldImp, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldArt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGrid, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGap(26, 26, 26)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)))
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldDom, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jTextFieldLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8)
                                        .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(46, 46, 46))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPaneArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jTextFieldUnid, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(89, 89, 89)
                                                .addComponent(jLabel14))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButtonCancelPed)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollBarArticulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGrid))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUnid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldImp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFactura)
                    .addComponent(jButtonAcept)
                    .addComponent(jButtonExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelPed)
                    .addComponent(jButtonCancel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollBarArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneArticulos, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGridActionPerformed
        /* La siguiente línea se utiliza para descargar el contenido del objeto de 
           la memoria. De esta forma, si se pulsa varias veces este botón, el objeto
           es refrescado.
        */
        jScrollPaneArticulos.setVisible(false);
        Vector vTitColum=new Vector();
        vTitColum.addElement("Código");
        vTitColum.addElement("Descripción");
        vTitColum.addElement("Stock");
        vTitColum.addElement("Precio");
        vArticulos=GestorBD.getTodosLosArticulos();
    }//GEN-LAST:event_jButtonGridActionPerformed

    private void jMenuItemClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClientesActionPerformed
        op = "clientes";
        jTextFieldCod.setEnabled(true);
        jTextFieldCod.grabFocus();
    }//GEN-LAST:event_jMenuItemClientesActionPerformed

    private void jMenuItemProveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProveActionPerformed
       op = "proveedores";
       jTextFieldCod.setEnabled(true);
       jTextFieldCod.grabFocus();
    }//GEN-LAST:event_jMenuItemProveActionPerformed

    private void jTextFieldCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodKeyPressed
        if(evt.getKeyCode()==10){
            try {
                rellenarCodigo();
                if(op.equals("clientes")){
                    try {
                        if(consultaCodigoClientes()){
                            estadoHabilitar();
                            String [] datos = bd.sacarDatos(jTextFieldCod.getText(), op);
                            jTextFieldNif.setText(datos[0]);
                            jTextFieldApe.setText(datos[1]);
                            jTextFieldNombre.setText(datos[2]);
                            jTextFieldDom.setText(datos[3]);
                            jTextFieldCp.setText(datos[4]);
                            jTextFieldLoc.setText(datos[5]);                              
                            jTextFieldArt.grabFocus();
                            jTextFieldCod.setEnabled(false);
                        }else{
                            JOptionPane.showMessageDialog(rootPane,"El código del cliente no existe.", "ERROR", JOptionPane.ERROR_MESSAGE);
                            jTextFieldCod.setText("");
                            jTextFieldCod.grabFocus();
                        }
                    } catch (SQLException ex) {
                        System.out.print(ex.getMessage());
                    }
                }else if(op.equals("proveedores")){
                    try {
                        if(consultaCodigoProveedores()){
                            estadoHabilitar();
                            String [] datos = bd.sacarDatos(jTextFieldCod.getText(), op);
                            jTextFieldNif.setText(datos[0]);
                            jTextFieldApe.setText(datos[1]);
                            jTextFieldNombre.setText(datos[2]);
                            jTextFieldDom.setText(datos[3]);
                            jTextFieldCp.setText(datos[4]);
                            jTextFieldLoc.setText(datos[5]);  
                            jTextFieldArt.grabFocus();
                            jTextFieldCod.setEnabled(false);
                        }else{
                            JOptionPane.showMessageDialog(rootPane,"El código del proveedor no existe.", "ERROR", JOptionPane.ERROR_MESSAGE);
                            jTextFieldCod.setText("");
                            jTextFieldCod.grabFocus();
                        }
                    } catch (SQLException ex) {
                        System.out.print(ex.getMessage());
                    }
                }
            } catch (Exception ex) {
                System.out.print(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jTextFieldCodKeyPressed

    

    // Initial state
    private void estadoInicial(){
        // Disable buttons
        jButtonAcept.setEnabled(false);
        jButtonCancel.setEnabled(false);
        jButtonCancelPed.setEnabled(false);
        jButtonExit.setEnabled(false);
        jButtonFactura.setEnabled(false);
        jButtonGrid.setEnabled(false);
      
        // Disable TextFields
        jTextFieldApe.setEnabled(false);
        jTextFieldArt.setEnabled(false);
        jTextFieldCod.setEnabled(false);
        jTextFieldCp.setEnabled(false);
        jTextFieldDesc.setEnabled(false);
        jTextFieldDom.setEnabled(false);
        jTextFieldImp.setEnabled(false);
        jTextFieldLoc.setEnabled(false);
        jTextFieldNif.setEnabled(false);
        jTextFieldNombre.setEnabled(false);
        jTextFieldPrecio.setEnabled(false);
        jTextFieldStock.setEnabled(false);
        jTextFieldTotal.setEnabled(false);
        jTextFieldUnid.setEnabled(false);
        
        // Disable Table
        jTable1.setEnabled(false);
        
        // Enable Menu
        jMenuBar1.setEnabled(true);
        jMenuItemClientes.setEnabled(true);
        jMenuItemProve.setEnabled(true);
        jMenuItemReturn.setEnabled(true);
    }
    
    // Enable state
    private void estadoHabilitar(){
         // Disable buttons
        jButtonAcept.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonCancelPed.setEnabled(true);
        jButtonExit.setEnabled(true);
        jButtonFactura.setEnabled(true);
        jButtonGrid.setEnabled(true);
      
        // Disable Client/Prov TextFields and Enable Articles TextFields
        jTextFieldApe.setEnabled(false);
        jTextFieldArt.setEnabled(true);
        jTextFieldCod.setEnabled(false);
        jTextFieldCp.setEnabled(false);
        jTextFieldDesc.setEnabled(true);
        jTextFieldDom.setEnabled(false);
        jTextFieldImp.setEnabled(true);
        jTextFieldLoc.setEnabled(false);
        jTextFieldNif.setEnabled(false);
        jTextFieldNombre.setEnabled(false);
        jTextFieldPrecio.setEnabled(true);
        jTextFieldStock.setEnabled(true);
        jTextFieldTotal.setEnabled(false);
        jTextFieldUnid.setEnabled(true);
        
        // Enable Table
        jTable1.setEnabled(true);
        
        // Disable Menu
        jMenuBar1.setEnabled(false);
        jMenuItemClientes.setEnabled(false);
        jMenuItemProve.setEnabled(false);
        jMenuItemReturn.setEnabled(false);
    }
    
    // Consult table code "Clientes"
    private boolean consultaCodigoClientes() throws SQLException {
        String sentencia = "select Código from clientes;";
        ResultSet listaMovimientos = st.executeQuery(sentencia);
        while (listaMovimientos.next()) {
            String cod = listaMovimientos.getString("Código");
            //JOptionPane.showMessageDialog(null, cod);
            if(cod.equals(jTextFieldCod.getText())){
                return true;
            }
        }
        return false;    
    }
    
    // Consult table code "Proveedores"
    private boolean consultaCodigoProveedores() throws SQLException {
        String sentencia = "select Código from proveedores;";
        ResultSet listaMovimientos = st.executeQuery(sentencia);
        while (listaMovimientos.next()) {
            String cod = listaMovimientos.getString("Código");
            //JOptionPane.showMessageDialog(null, cod);
            if(cod.equals(jTextFieldCod.getText())){
                return true;
            }
        }
        return false;    
    }
    
    // Fill code
    private void rellenarCodigo() throws Exception {
        String code=jTextFieldCod.getText();
        if(jTextFieldCod.getText().matches("[a-zA-Z0-9]{1,6}")){
            while(code.length()!=6)
            {
                code="0"+code;
            }
            jTextFieldCod.setText(code);
        }else{
            JOptionPane.showMessageDialog(rootPane, "El código tiene que tener como mucho 6 números/letras.", code, WIDTH);
            throw new Exception("");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAcept;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonCancelPed;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonGrid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemClientes;
    private javax.swing.JMenuItem jMenuItemProve;
    private javax.swing.JMenuItem jMenuItemReturn;
    private javax.swing.JMenu jMenuPedidos;
    private javax.swing.JScrollBar jScrollBarArticulos;
    private javax.swing.JScrollPane jScrollPaneArticulos;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldApe;
    private javax.swing.JTextField jTextFieldArt;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldDesc;
    private javax.swing.JTextField jTextFieldDom;
    private javax.swing.JTextField jTextFieldImp;
    private javax.swing.JTextField jTextFieldLoc;
    private javax.swing.JTextField jTextFieldNif;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    private javax.swing.JTextField jTextFieldTotal;
    private javax.swing.JTextField jTextFieldUnid;
    // End of variables declaration//GEN-END:variables

    
}
