/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestiondeunalmacen;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Frans
 */
public class Formulario extends javax.swing.JFrame {
    static javax.swing.JFrame padre;
    private GestorBD bd;
    /**
     * Creates new form JFrameFormulario
     */
    public Formulario(javax.swing.JFrame padre) {
        Formulario.padre=padre;
        initComponents();
        setTitle("Gestión de Almacén - Clientes");
        estadoInicial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuMan = new javax.swing.JMenu();
        jMenuItemAltas = new javax.swing.JMenuItem();
        jMenuItemBajas = new javax.swing.JMenuItem();
        jMenuItemMod = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemVolver = new javax.swing.JMenuItem();
        jMenuCon = new javax.swing.JMenu();
        jMenuItemCod = new javax.swing.JMenuItem();
        jMenuList = new javax.swing.JMenu();
        jMenuItemCodigo = new javax.swing.JMenuItem();
        jMenuItemEntre = new javax.swing.JMenuItem();
        jMenuItemGraf = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Código");

        jLabel2.setText("NIF");

        jLabel3.setText("Nombre");

        jTextFieldCod.setColumns(6);
        jTextFieldCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodActionPerformed(evt);
            }
        });
        jTextFieldCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldCodKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodKeyPressed(evt);
            }
        });

        jTextField2.setColumns(7);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField2KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setColumns(1);
        jTextField3.setEnabled(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setColumns(15);
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jLabel4.setText("Apellidos");

        jLabel5.setText("Domicilio");

        jLabel6.setText("C.P.");

        jLabel7.setText("Localidad");

        jLabel8.setText("Teléfono");

        jLabel9.setText("Móvil");

        jLabel10.setText("Fax");

        jTextField5.setColumns(35);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.setColumns(40);
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jTextField6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField6KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField6KeyTyped(evt);
            }
        });

        jTextField7.setColumns(4);
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jTextField7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField7KeyTyped(evt);
            }
        });

        jTextField8.setColumns(20);
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jTextField8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField8KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField8KeyTyped(evt);
            }
        });

        jTextField9.setColumns(7);
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });
        jTextField9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField9KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField9KeyTyped(evt);
            }
        });

        jTextField10.setColumns(7);
        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jTextField10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField10KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField10KeyTyped(evt);
            }
        });

        jTextField11.setColumns(7);
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField11KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });

        jLabel11.setText("E-mail");

        jLabel12.setText("Total Ventas");

        jTextField12.setColumns(20);
        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });
        jTextField12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField12KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField12KeyTyped(evt);
            }
        });

        jTextField13.setColumns(1);
        jTextField13.setText("0");
        jTextField13.setEnabled(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jButton1.setMnemonic('a');
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setMnemonic('c');
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonExit.setMnemonic('s');
        jButtonExit.setText("Salir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jMenuMan.setMnemonic('m');
        jMenuMan.setText("Mantenimiento");

        jMenuItemAltas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemAltas.setMnemonic('a');
        jMenuItemAltas.setText("Altas");
        jMenuItemAltas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAltasActionPerformed(evt);
            }
        });
        jMenuMan.add(jMenuItemAltas);

        jMenuItemBajas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemBajas.setMnemonic('b');
        jMenuItemBajas.setText("Bajas");
        jMenuMan.add(jMenuItemBajas);

        jMenuItemMod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemMod.setMnemonic('m');
        jMenuItemMod.setText("Modificaciones");
        jMenuMan.add(jMenuItemMod);
        jMenuMan.add(jSeparator1);

        jMenuItemVolver.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemVolver.setMnemonic('v');
        jMenuItemVolver.setText("Volver");
        jMenuItemVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemVolverActionPerformed(evt);
            }
        });
        jMenuMan.add(jMenuItemVolver);

        jMenuBar1.add(jMenuMan);

        jMenuCon.setMnemonic('c');
        jMenuCon.setText("Consultas");

        jMenuItemCod.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCod.setMnemonic('p');
        jMenuItemCod.setText("Por Código");
        jMenuCon.add(jMenuItemCod);

        jMenuList.setMnemonic('l');
        jMenuList.setText("Listados");

        jMenuItemCodigo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemCodigo.setMnemonic('p');
        jMenuItemCodigo.setText("Por Código");
        jMenuList.add(jMenuItemCodigo);

        jMenuItemEntre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemEntre.setMnemonic('e');
        jMenuItemEntre.setText("Entre Códigos");
        jMenuList.add(jMenuItemEntre);

        jMenuItemGraf.setMnemonic('g');
        jMenuItemGraf.setText("Gráficos");
        jMenuList.add(jMenuItemGraf);

        jMenuCon.add(jMenuList);

        jMenuBar1.add(jMenuCon);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel2))
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField13)))
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButtonExit))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTextFieldCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodActionPerformed
        // TODO add your handling code here:  
    }//GEN-LAST:event_jTextFieldCodActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    boolean verdadero=true;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        validacionCodigo();
        if(verdadero){
        validacionNIF();
        }
        if(verdadero){
        sacarletra();
        }
        if(verdadero){
        validacionNombre();
        }
        if(verdadero){
        validacionApellidos();
        }
        if(verdadero){
        validacionDomicilio();
        }
        if(verdadero){
        validacionCP();
        }
        if(verdadero){
        validacionLocalidad();
        }
        if(verdadero){
        validacionTelefono();
        }
        if(verdadero){
        validacionMovil();
        }
        if(verdadero){
        validacionFax();
        }
        if(verdadero){
        validacionCorreo();
        }
        if(verdadero){
            JOptionPane.showMessageDialog(this, "Todo correcto", "Información de datos", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCod.setText(null);
            jTextField2.setText(null);
            jTextField3.setText(null);
            jTextField4.setText(null);
            jTextField5.setText(null);
            jTextField6.setText(null);
            jTextField7.setText(null);
            jTextField8.setText(null);
            jTextField9.setText(null);
            jTextField10.setText(null);
            jTextField11.setText(null);
            jTextField12.setText(null);
            jTextFieldCod.grabFocus();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextFieldCod.setText(null);
        jTextField2.setText(null);
        jTextField3.setText(null);
        jTextField4.setText(null);
        jTextField5.setText(null);
        jTextField6.setText(null);
        jTextField7.setText(null);
        jTextField8.setText(null);
        jTextField9.setText(null);
        jTextField10.setText(null);
        jTextField11.setText(null);
        jTextField12.setText(null);
        jTextFieldCod.grabFocus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField2.grabFocus();
            validacionCodigo();
            //if(bd.valCod(jTextFieldCod.getText()))
                estadoAltas();
        }
    }//GEN-LAST:event_jTextFieldCodKeyPressed

    private void jTextFieldCodKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodKeyTyped
        // TODO add your handling code here:
        int limite=6;
        if(jTextFieldCod.getText().length()==limite){
            evt.consume();
        }
  
    }//GEN-LAST:event_jTextFieldCodKeyTyped

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyTyped
        // TODO add your handling code here:
        int limite=8;
        if(jTextField2.getText().length()==limite){
            //evt.consume();
            jTextField4.grabFocus();
        }
    }//GEN-LAST:event_jTextField2KeyTyped

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        // TODO add your handling code here:
        int limite=35;
        if(jTextField5.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        // TODO add your handling code here:
        int limite=15;
        if(jTextField4.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jTextField6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyTyped
        // TODO add your handling code here:
        int limite=40;
        if(jTextField6.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField6KeyTyped

    private void jTextField7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyTyped
        // TODO add your handling code here:
        int limite=5;
        if(jTextField7.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField7KeyTyped

    private void jTextField8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(jTextField8.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField8KeyTyped

    private void jTextField9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyTyped
        // TODO add your handling code here:
        int limite=9;
        if(jTextField9.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField9KeyTyped

    private void jTextField10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyTyped
        // TODO add your handling code here:
        int limite=9;
        if(jTextField10.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField10KeyTyped

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
        // TODO add your handling code here:
        int limite=9;
        if(jTextField11.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField11KeyTyped

    private void jTextField12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyTyped
        // TODO add your handling code here:
        int limite=20;
        if(jTextField12.getText().length()==limite){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField12KeyTyped

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField4.grabFocus();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField5.grabFocus();
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField6.grabFocus();
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField6KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField7.grabFocus();
        }
    }//GEN-LAST:event_jTextField6KeyPressed

    private void jTextField7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField7KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField8.grabFocus();
        }
    }//GEN-LAST:event_jTextField7KeyPressed

    private void jTextField8KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField8KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField9.grabFocus();
        }
    }//GEN-LAST:event_jTextField8KeyPressed

    private void jTextField9KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField9KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField10.grabFocus();
        }
    }//GEN-LAST:event_jTextField9KeyPressed

    private void jTextField10KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField10KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField11.grabFocus();
        }
    }//GEN-LAST:event_jTextField10KeyPressed

    private void jTextField11KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jTextField12.grabFocus();
        }
    }//GEN-LAST:event_jTextField11KeyPressed

    private void jTextField12KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField12KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==10){
            jButton1.grabFocus();
        }
    }//GEN-LAST:event_jTextField12KeyPressed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
       estadoInicial();
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jMenuItemVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemVolverActionPerformed
        this.setVisible(false);
        padre.setEnabled(true);
    }//GEN-LAST:event_jMenuItemVolverActionPerformed

    private void jMenuItemAltasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAltasActionPerformed
        estadoABMC();
    }//GEN-LAST:event_jMenuItemAltasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario(padre).setVisible(true);
            }
        });
    }
    protected void processWindowEvent(java.awt.event.WindowEvent e) {
        super.processWindowEvent(e);
        if (e.getID() == java.awt.event.WindowEvent.WINDOW_CLOSING) {
            padre.setEnabled(true);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCon;
    private javax.swing.JMenuItem jMenuItemAltas;
    private javax.swing.JMenuItem jMenuItemBajas;
    private javax.swing.JMenuItem jMenuItemCod;
    private javax.swing.JMenuItem jMenuItemCodigo;
    private javax.swing.JMenuItem jMenuItemEntre;
    private javax.swing.JMenuItem jMenuItemGraf;
    private javax.swing.JMenuItem jMenuItemMod;
    private javax.swing.JMenuItem jMenuItemVolver;
    private javax.swing.JMenu jMenuList;
    private javax.swing.JMenu jMenuMan;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldCod;
    // End of variables declaration//GEN-END:variables

    private void validacionCodigo() {
        String Codigo=jTextFieldCod.getText();
        if(Codigo.matches("([A-Z]*[a-z]*[0-9]*){6}") || Codigo==""){
            verdadero=true;
            if(Codigo.length()<6){
                int longitud=6-Codigo.length();
                    String ceros="";
                    if(longitud==1){
                        ceros=ceros+"0";
                    }
                    if(longitud==2){
                        ceros=ceros+"00";
                    }
                    if(longitud==3){
                        ceros=ceros+"000";
                    }
                    if(longitud==4){
                        ceros=ceros+"0000";
                    }
                    if(longitud==5){
                        ceros=ceros+"00000";
                    }
                    if(longitud==6){
                        JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Código", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                        jTextFieldCod.setText(null);
                        jTextFieldCod.grabFocus();
                        verdadero=false;
                    }
            Codigo=ceros.concat(Codigo);
            jTextFieldCod.setText(Codigo);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Código", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextFieldCod.setText(null);
            jTextFieldCod.grabFocus();
            verdadero=false;
        }
    }

    private void validacionNIF() {
        String NIF=jTextField2.getText();
        if(NIF.matches("[0-9]{8}") || NIF==null){
            if(NIF==null){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en NIF", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField2.setText(null);
                jTextField2.grabFocus();
                verdadero=false;
            }
            verdadero=true;
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en NIF", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField2.setText(null);
            jTextField2.grabFocus();
            verdadero=false;
        }
    }
    
     private void sacarletra() {
        String NIF_STRING_ASOCIATION = "TRWAGMYFPDXBNJZSQVHLCKE";
        int letra=Integer.valueOf(jTextField2.getText()) % 23;
        jTextField3.setText(""+NIF_STRING_ASOCIATION.charAt(letra));
        
    }

    private void validacionNombre() {
        String Nombre=jTextField4.getText();
        if(Nombre.matches("([A-Z]*[a-z]*[ñÑ .ÁÉÍÓÚáéíóúÀÈÌÒÙàèìòù]*){15}") || Nombre.equals("")){
            verdadero=true;
            if(Nombre.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Nombre", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField4.setText(null);
                jTextField4.grabFocus();
                verdadero=false;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Nombre", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField4.setText(null);
            jTextField4.grabFocus();
            verdadero=false;
        }
    }

    private void validacionApellidos() {
        String Apellidos=jTextField5.getText();
        if(Apellidos.matches("([A-Z]*[a-z]*[ñÑ .ÁÉÍÓÚáéíóúÀÈÌÒÙàèìòù-]*){35}") || Apellidos.equals("")){
            verdadero=true;
            if(Apellidos.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Apellidos", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField5.setText(null);
                jTextField5.grabFocus();
                verdadero=false;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Apellidos", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField5.setText(null);
            jTextField5.grabFocus();
            verdadero=false;
        }
    }

    private void validacionDomicilio() {
        String Domicilio=jTextField6.getText();
        if(Domicilio.matches("([A-Z]*[a-z]*[0-9]*[ñÑ .ÁÉÍÓÚáéíóúÀÈÌÒÙàèìòù-]*[ºª/,]*){35}") || Domicilio.equals("")){
            verdadero=true;
            if(Domicilio.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Domicilio", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField6.setText(null);
                jTextField6.grabFocus();
                verdadero=false;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Domicilio", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField6.setText(null);
            jTextField6.grabFocus();
            verdadero=false;
        }
    }

    private void validacionCP() {
        String CP=jTextField7.getText();
        if(CP.matches("[0-9]{5}") || CP.equals("")){
            verdadero=true;
            if(CP.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en C.P.", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField7.setText(null);
                jTextField7.grabFocus();
                verdadero=false;
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en C.P.", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField7.setText(null);
            jTextField7.grabFocus();
            verdadero=false;
        }
    }

    private void validacionLocalidad() {
        String Localidad=jTextField8.getText();
        if(Localidad.matches("([A-Z]*[a-z]*[ñÑ .ÁÉÍÓÚáéíóúÀÈÌÒÙàèìòù-]*){20}") || Localidad.equals("")){
            verdadero=true;
            if(Localidad.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Localidad", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField8.setText(null);
                jTextField8.grabFocus();
                verdadero=false;
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Localidad", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField8.setText(null);
            jTextField8.grabFocus();
            verdadero=false;
        }
    }

    private void validacionTelefono() {
        String Tlf=jTextField9.getText();
        if(Tlf.matches("[0-9]{9}") || Tlf.equals("")){
            verdadero=true;
            if(Tlf.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Teléfono", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField9.setText(null);
                jTextField9.grabFocus();
                verdadero=false;
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Teléfono", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField9.setText(null);
            jTextField9.grabFocus();
            verdadero=false;
        }
    }

    private void validacionMovil() {
        String Movil=jTextField10.getText();
        if(Movil.matches("[0-9]{9}") || Movil.equals("")){
            verdadero=true;
            if(Movil.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Móvil", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField10.setText(null);
                jTextField10.grabFocus();
                verdadero=false;
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Móvil", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField10.setText(null);
            jTextField10.grabFocus();
            verdadero=false;
        }
    }

    private void validacionFax() {
        String Fax=jTextField11.getText();
        if(Fax.matches("[0-9]{9}") || Fax.equals("")){
            verdadero=true;
            if(Fax.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Fax", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField11.setText(null);
                jTextField11.grabFocus();
                verdadero=false;
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en Fax", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField11.setText(null);
            jTextField11.grabFocus();
            verdadero=false;
        }
    }

    private void validacionCorreo() {
        String Email=jTextField12.getText();
        if(Email.matches("([A-Z]*[a-z]*[0-9]*[ñÑ .ÁÉÍÓÚáéíóúÀÈÌÒÙàèìòù-]*[_@]*){20}") || Email.equals("")){
            verdadero=true;
            if(Email.equals("")){
                JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en E-mail", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
                jTextField12.setText(null);
                jTextField12.grabFocus();
                verdadero=false;
            }  
        }else{
            JOptionPane.showMessageDialog(this, "Aviso, datos vacios o erroneos en E-mail", "Datos incorrectos", JOptionPane.INFORMATION_MESSAGE);
            jTextField12.setText(null);
            jTextField12.grabFocus();
            verdadero=false;
        }
    }

    private void estadoInicial() {
        jTextFieldCod.setText("");
        jTextFieldCod.setEnabled(false);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField10.setEnabled(false);
        jTextField11.setEnabled(false);
        jTextField12.setEnabled(false);
        jTextField13.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButtonExit.setEnabled(false);
        jMenuBar1.setEnabled(true);
        jMenuCon.setEnabled(true);
        jMenuItemAltas.setEnabled(true);
        jMenuItemBajas.setEnabled(true);
        jMenuItemCod.setEnabled(true);
        jMenuItemCodigo.setEnabled(true);
        jMenuItemEntre.setEnabled(true);
        jMenuItemGraf.setEnabled(true);
        jMenuItemMod.setEnabled(true);
        jMenuItemVolver.setEnabled(true);
        jMenuList.setEnabled(true);
        jMenuMan.setEnabled(true);
        jMenuBar1.grabFocus();
    }
    
    private void estadoABMC() {
        jTextFieldCod.setEnabled(true);
        jTextField2.setEnabled(false);
        jTextField3.setEnabled(false);
        jTextField4.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
        jTextField7.setEnabled(false);
        jTextField8.setEnabled(false);
        jTextField9.setEnabled(false);
        jTextField10.setEnabled(false);
        jTextField11.setEnabled(false);
        jTextField12.setEnabled(false);
        jTextField13.setEnabled(false);
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButtonExit.setEnabled(true);
        jMenuBar1.setEnabled(true);
        jMenuCon.setEnabled(true);
        jMenuItemAltas.setEnabled(true);
        jMenuItemBajas.setEnabled(true);
        jMenuItemCod.setEnabled(true);
        jMenuItemCodigo.setEnabled(true);
        jMenuItemEntre.setEnabled(true);
        jMenuItemGraf.setEnabled(true);
        jMenuItemMod.setEnabled(true);
        jMenuItemVolver.setEnabled(true);
        jMenuList.setEnabled(true);
        jMenuMan.setEnabled(true);
        jTextFieldCod.grabFocus();
    }

    private void estadoAltas() {
        jTextFieldCod.setEnabled(false);
        jTextField2.setEnabled(true);
        jTextField3.setEnabled(true);
        jTextField4.setEnabled(true);
        jTextField5.setEnabled(true);
        jTextField6.setEnabled(true);
        jTextField7.setEnabled(true);
        jTextField8.setEnabled(true);
        jTextField9.setEnabled(true);
        jTextField10.setEnabled(true);
        jTextField11.setEnabled(true);
        jTextField12.setEnabled(true);
        jTextField13.setEnabled(true);
        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButtonExit.setEnabled(true);
        jMenuBar1.setEnabled(true);
        jMenuCon.setEnabled(true);
        jMenuItemAltas.setEnabled(true);
        jMenuItemBajas.setEnabled(true);
        jMenuItemCod.setEnabled(true);
        jMenuItemCodigo.setEnabled(true);
        jMenuItemEntre.setEnabled(true);
        jMenuItemGraf.setEnabled(true);
        jMenuItemMod.setEnabled(true);
        jMenuItemVolver.setEnabled(true);
        jMenuList.setEnabled(true);
        jMenuMan.setEnabled(true);
        jTextField2.grabFocus();
    }
}

