/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventas;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author Frans Kuijper
 */
public class VentaDeOrdenadores extends javax.swing.JFrame {

    public ArrayList<Venta> ventas = new ArrayList<>();
    /**
     * Creates new form VentaDeOrdenadores
     */
    public VentaDeOrdenadores() {
        initComponents();      
        estadoInicial();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxLocalidad = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        jRadioButton12 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jCheckBoxDvD = new javax.swing.JCheckBox();
        jCheckBoxWifi = new javax.swing.JCheckBox();
        jCheckBoxTV = new javax.swing.JCheckBox();
        jCheckBoxRestore = new javax.swing.JCheckBox();
        jButtonAdd = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del cliente");

        jTextFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldNombreMouseClicked(evt);
            }
        });
        jTextFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreActionPerformed(evt);
            }
        });
        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setText("Localidad");

        jComboBoxLocalidad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jComboBoxLocalidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Villalba", "Alpedrete", "Galapagar", "Guadarrama", "Moralzarzal" }));
        jComboBoxLocalidad.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setText("Lista de clientes");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel4.setText("Procesador");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton1.setText("P4 3.0 Gb");
        jRadioButton1.setEnabled(false);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton2.setText("P4 3.2 Gb");
        jRadioButton2.setEnabled(false);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("P4 Celeron");
        jRadioButton3.setEnabled(false);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton4.setText("AMD 650");
        jRadioButton4.setEnabled(false);

        jLabel5.setText("Memoria");

        buttonGroup2.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton5.setText("128 Mb");
        jRadioButton5.setEnabled(false);

        buttonGroup2.add(jRadioButton6);
        jRadioButton6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton6.setText("256 Mb");
        jRadioButton6.setEnabled(false);

        buttonGroup2.add(jRadioButton7);
        jRadioButton7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton7.setText("512 Mb");
        jRadioButton7.setEnabled(false);

        buttonGroup2.add(jRadioButton8);
        jRadioButton8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton8.setSelected(true);
        jRadioButton8.setText("1024 Mb");
        jRadioButton8.setEnabled(false);

        jLabel6.setText("Monitor");

        buttonGroup3.add(jRadioButton9);
        jRadioButton9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton9.setText("15\"");
        jRadioButton9.setEnabled(false);

        buttonGroup3.add(jRadioButton10);
        jRadioButton10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton10.setText("17\"");
        jRadioButton10.setEnabled(false);

        buttonGroup3.add(jRadioButton11);
        jRadioButton11.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton11.setText("TFT 15\"");
        jRadioButton11.setEnabled(false);

        buttonGroup3.add(jRadioButton12);
        jRadioButton12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton12.setSelected(true);
        jRadioButton12.setText("TFT 17\"");
        jRadioButton12.setEnabled(false);

        jLabel7.setText("Disco Duro");

        buttonGroup4.add(jRadioButton13);
        jRadioButton13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton13.setText("60 Gb");
        jRadioButton13.setEnabled(false);

        buttonGroup4.add(jRadioButton14);
        jRadioButton14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton14.setText("80 Gb");
        jRadioButton14.setEnabled(false);

        buttonGroup4.add(jRadioButton15);
        jRadioButton15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton15.setText("120 Gb");
        jRadioButton15.setEnabled(false);

        buttonGroup4.add(jRadioButton16);
        jRadioButton16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jRadioButton16.setSelected(true);
        jRadioButton16.setText("200 Gb");
        jRadioButton16.setEnabled(false);

        jLabel8.setText("Opciones");

        jCheckBoxDvD.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxDvD.setSelected(true);
        jCheckBoxDvD.setText("Grabadora DVD");
        jCheckBoxDvD.setEnabled(false);

        jCheckBoxWifi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxWifi.setSelected(true);
        jCheckBoxWifi.setText("Wifi");
        jCheckBoxWifi.setEnabled(false);

        jCheckBoxTV.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxTV.setText("Sintonizador TV");
        jCheckBoxTV.setEnabled(false);

        jCheckBoxRestore.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jCheckBoxRestore.setText("Backup/Restore");
        jCheckBoxRestore.setEnabled(false);

        jButtonAdd.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonAdd.setMnemonic('a');
        jButtonAdd.setText("Añadir");
        jButtonAdd.setEnabled(false);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonBuscar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonBuscar.setMnemonic('b');
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.setEnabled(false);
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jButtonDelete.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonDelete.setMnemonic('e');
        jButtonDelete.setText("Eliminar");
        jButtonDelete.setEnabled(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonCancel.setMnemonic('c');
        jButtonCancel.setText("Cancelar");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonExit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jButtonExit.setMnemonic('s');
        jButtonExit.setText("Salir");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton7)
                            .addComponent(jRadioButton6)
                            .addComponent(jRadioButton8))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton10)
                            .addComponent(jRadioButton11)
                            .addComponent(jRadioButton12))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButton15)
                                    .addComponent(jRadioButton14)
                                    .addComponent(jRadioButton16)
                                    .addComponent(jRadioButton13))
                                .addGap(146, 146, 146)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxDvD)
                                    .addComponent(jCheckBoxRestore)
                                    .addComponent(jCheckBoxTV)
                                    .addComponent(jCheckBoxWifi))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addGap(36, 36, 36)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxLocalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton5)
                            .addComponent(jRadioButton9)
                            .addComponent(jRadioButton13)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBoxDvD)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton10)
                    .addComponent(jRadioButton14)
                    .addComponent(jCheckBoxWifi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton11)
                    .addComponent(jRadioButton15)
                    .addComponent(jCheckBoxTV))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton12)
                    .addComponent(jRadioButton16)
                    .addComponent(jCheckBoxRestore))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        aniadir();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        buscar();  
        estadoInicial();
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        estadoInicial();     
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //Volver al estado inicial.
        estadoInicial();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
       //Salir del programa
       System.exit(0);
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
         //Al pulsar ENTER en la posición de la caja de texto del nombre.
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(jTextFieldNombre.getText().equals("")){
                JOptionPane.showMessageDialog(this, "La caja de texto del nomnbre no puede estar vacía.", "ERROR.", JOptionPane.ERROR_MESSAGE);
            }
            else{
                if(jTextFieldNombre.getText().length()>15){
                    JOptionPane.showMessageDialog(this, "La caja de texto no admite más de 15 carácteres.", "ERROR.", JOptionPane.ERROR_MESSAGE);
                }else{
                    if(!validarNombre(jTextFieldNombre.getText())){
                        JOptionPane.showMessageDialog(this, "La caja de texto no admite carácteres especiales(números, símbolos, barras, etc).", "ERROR.", JOptionPane.ERROR_MESSAGE);
                        estadoInicial();
                    }else{
                        estado2();
                    }
                }
            }
        }
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if(!ventas.isEmpty()){
            jButtonDelete.setEnabled(true);
            jButtonAdd.setEnabled(false);
            jButtonBuscar.setEnabled(false);
            String nombre=jList1.getSelectedValuesList().toString();
            nombre = nombre.replace("[","");
            nombre = nombre.replace("]","");
            jTextFieldNombre.setText(nombre);
                try{
                    if(ventas.get(jList1.getSelectedIndex()).getCliente().equals(nombre)){
                        dibujaVentas(ventas.get(jList1.getSelectedIndex()));
                }
                }catch(Exception e){
                    
                }
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jTextFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreActionPerformed
        estadoInicial();
    }//GEN-LAST:event_jTextFieldNombreActionPerformed

    private void jTextFieldNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldNombreMouseClicked
        estadoInicial();
    }//GEN-LAST:event_jTextFieldNombreMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaDeOrdenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaDeOrdenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaDeOrdenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaDeOrdenadores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaDeOrdenadores().setVisible(true);
            }
        });
    }

    private void estadoInicial(){
        //Todo deshabilitado menos Caja de texto del Nombre, la Lista de Clientes y los Botones de Cancelar y Salir. 
        jTextFieldNombre.setEnabled(true);
        jComboBoxLocalidad.setEnabled(false);
        jButtonAdd.setEnabled(false);
        jButtonBuscar.setEnabled(false);
        jButtonCancel.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonExit.setEnabled(true);
        jRadioButton1.setEnabled(false);
        jRadioButton2.setEnabled(false);
        jRadioButton3.setEnabled(false);
        jRadioButton4.setEnabled(false);
        jRadioButton5.setEnabled(false);
        jRadioButton6.setEnabled(false);
        jRadioButton7.setEnabled(false);
        jRadioButton8.setEnabled(false);
        jRadioButton9.setEnabled(false);
        jRadioButton10.setEnabled(false);
        jRadioButton11.setEnabled(false);
        jRadioButton12.setEnabled(false);
        jRadioButton13.setEnabled(false);
        jRadioButton14.setEnabled(false);
        jRadioButton15.setEnabled(false);
        jRadioButton16.setEnabled(false);
        jCheckBoxDvD.setEnabled(false);
        jCheckBoxTV.setEnabled(false);
        jCheckBoxRestore.setEnabled(false);
        jCheckBoxWifi.setEnabled(false);
        jList1.setEnabled(true);
        jRadioButton3.setSelected(true);
        jRadioButton8.setSelected(true);
        jRadioButton12.setSelected(true);
        jRadioButton16.setSelected(true);
        jTextFieldNombre.setText("");
        jTextFieldNombre.grabFocus();
        jCheckBoxWifi.setSelected(true);
        jCheckBoxDvD.setSelected(true);
        jCheckBoxRestore.setSelected(false);
        jCheckBoxTV.setSelected(false);
        jTextFieldNombre.grabFocus();
        jComboBoxLocalidad.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JCheckBox jCheckBoxDvD;
    private javax.swing.JCheckBox jCheckBoxRestore;
    private javax.swing.JCheckBox jCheckBoxTV;
    private javax.swing.JCheckBox jCheckBoxWifi;
    private javax.swing.JComboBox jComboBoxLocalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables

    private void estado2() {
        jTextFieldNombre.setEnabled(false);
        jComboBoxLocalidad.setEnabled(true);
        jButtonAdd.setEnabled(true);
        jButtonBuscar.setEnabled(true);
        jButtonCancel.setEnabled(true);
        jButtonDelete.setEnabled(false);
        jButtonExit.setEnabled(true);
        jRadioButton1.setEnabled(true);
        jRadioButton2.setEnabled(true);
        jRadioButton3.setEnabled(true);
        jRadioButton4.setEnabled(true);
        jRadioButton5.setEnabled(true);
        jRadioButton6.setEnabled(true);
        jRadioButton7.setEnabled(true);
        jRadioButton8.setEnabled(true);
        jRadioButton9.setEnabled(true);
        jRadioButton10.setEnabled(true);
        jRadioButton11.setEnabled(true);
        jRadioButton12.setEnabled(true);
        jRadioButton13.setEnabled(true);
        jRadioButton14.setEnabled(true);
        jRadioButton15.setEnabled(true);
        jRadioButton16.setEnabled(true);
        jCheckBoxDvD.setEnabled(true);
        jCheckBoxTV.setEnabled(true);
        jCheckBoxRestore.setEnabled(true);
        jCheckBoxWifi.setEnabled(true);
        jList1.setEnabled(true);
        jRadioButton3.setSelected(true);
        jRadioButton8.setSelected(true);
        jRadioButton12.setSelected(true);
        jRadioButton16.setSelected(true);
        jComboBoxLocalidad.setSelectedIndex(0);
        jComboBoxLocalidad.grabFocus(); //Foco en Localidad
       
    }

    private void aniadir() {      
        jList1.setListData(actualizarLista(jTextFieldNombre.getText()));
        estadoInicial();
    }

    public void dibujaVentas(Venta v){
        switch(v.getProcesador()){
            case 0:
                jRadioButton1.setSelected(true);
                break;
            case 1:
                jRadioButton2.setSelected(true);
                break;
            case 2:
                jRadioButton3.setSelected(true);
                break;
            case 3:
                jRadioButton4.setSelected(true);
                break;
        }
        switch(v.getMemoria()){
            case 0:
                jRadioButton5.setSelected(true);
                break;
            case 1:
                jRadioButton6.setSelected(true);
                break;
            case 2:
                jRadioButton7.setSelected(true);
                break;
            case 3:
                jRadioButton8.setSelected(true);
                break;
        }
        switch(v.getMonitor()){
            case 0:
                jRadioButton9.setSelected(true);
                break;
            case 1:
                jRadioButton10.setSelected(true);
                break;
            case 2:
                jRadioButton11.setSelected(true);
                break;
            case 3:
                jRadioButton12.setSelected(true);
                break;
        }
        switch(v.getDisco()){
            case 0:
                jRadioButton13.setSelected(true);
                break;
            case 1:
                jRadioButton14.setSelected(true);
                break;
            case 2:
                jRadioButton15.setSelected(true);
                break;
            case 3:
                jRadioButton16.setSelected(true);
                break;
        }
        if(v.isDvd()){
            jCheckBoxDvD.setSelected(true);
        }else{
            jCheckBoxDvD.setSelected(false);
        }
        if(v.isRestore()){
            jCheckBoxRestore.setSelected(true);
        }else{
            jCheckBoxRestore.setSelected(false);
        }
        if(v.isTv()){
            jCheckBoxTV.setSelected(true);
        }else{
            jCheckBoxTV.setSelected(false);
        }
        if(v.isWifi()){
            jCheckBoxWifi.setSelected(true);
        }else{
            jCheckBoxWifi.setSelected(false);
        }
        jComboBoxLocalidad.setSelectedIndex(v.getLocalidad());
    }
    
    //Busca una Venta del array Ventas según el nombre.
    public Venta sacarDatosVenta(String nombre, int celda) throws Exception{
        int aux=0;
        for(int i=0;i<ventas.size();i++){
            if(ventas.get(i).getCliente().equals(nombre)) {
                if(aux==celda){
                    return ventas.get(i); 
                }else {
                    aux++;
                }
            }
        }
        throw new Exception("No se ha encontrado");       
    }

    private String [] actualizarLista(String nombre) {
         //Vemos lo seleccionado en el formulario.
        int procesador = 2,memoria = 3,monitor = 3,disco = 3;
        if(jRadioButton1.isSelected())
            procesador=0;
        else if(jRadioButton2.isSelected())
            procesador=1;
                    else if(jRadioButton3.isSelected())          
                        procesador=2;
                    else if(jRadioButton4.isSelected())
                        procesador=3;
        if(jRadioButton5.isSelected())
            memoria=0;
        else if(jRadioButton6.isSelected())
            memoria=1;
                    else if(jRadioButton7.isSelected())          
                        memoria=2;
                    else if(jRadioButton8.isSelected())
                        memoria=3;
        if(jRadioButton9.isSelected())
            monitor=0;
        else if(jRadioButton10.isSelected())
            monitor=1;
                    else if(jRadioButton11.isSelected())          
                        monitor=2;
                    else if(jRadioButton12.isSelected())
                        monitor=3;
        if(jRadioButton13.isSelected())
            disco=0;
        else if(jRadioButton14.isSelected())
            disco=1;
                    else if(jRadioButton15.isSelected())          
                        disco=2;
                    else if(jRadioButton16.isSelected())
                        disco=3;
        //-- Después de ver las opciones seleccionadas, añadimos la nueva venta --//
        if(nombre!=null){
            ventas.add(new Venta(nombre,jComboBoxLocalidad.getSelectedIndex(),procesador,memoria,monitor,disco,
                jCheckBoxDvD.isSelected(),jCheckBoxWifi.isSelected(),jCheckBoxTV.isSelected(),jCheckBoxRestore.isSelected()));        }
        //Se crea un array para guardar los Nombres de los Clientes
        String[]listaClientes = new String[ventas.size()];
        //Guardamos los nombres de los clientes que han hecho una venta en el array listaClientes.
        for(int i=0; i<ventas.size();i++){
            listaClientes[i]=ventas.get(i).getCliente();
        }
        //Devolvemos la lista de clientes.
        return listaClientes;
    }

    private void buscar(){
        //Busca si hay ventas guardadas.
        int bus = 0; //Variable que indica si habrá o no más ventas del mismo nombre.
        if(ventas.isEmpty()){
            JOptionPane.showMessageDialog(this, "No hay ventas guardadas.", "ERROR DE VENTAS", JOptionPane.ERROR_MESSAGE);//Mensaje informativo.
        }else{
             try {
                dibujaVentas(sacarDatosVenta(jTextFieldNombre.getText(),bus));
                try{
                    if(!masVentas(jTextFieldNombre.getText()))
                        throw new Exception();
                    bus++;   
                     boolean salir = false;
                    do {                        
                        int opcion=JOptionPane.showConfirmDialog(null, "¿Quiere seguir mostrando ventas de este cliente?","¿Continuar?",JOptionPane.OK_CANCEL_OPTION);//Devuelve un valor entero según la opción que escojamos de la ventana.
                        switch(opcion){
                            case JOptionPane.OK_OPTION://Si das a "aceptar" en la ventana anterior muestra este mensaje.
                                    dibujaVentas(sacarDatosVenta(jTextFieldNombre.getText(),bus));
                                    break;
                            case JOptionPane.CANCEL_OPTION://Si das a "cancelar" en la ventana anterior muestra este mensaje.
                                    JOptionPane.showMessageDialog(this, "Búsqueda finalizada.");//Mensaje informativo.
                                    salir=true;
                                    break;
                            case JOptionPane.CLOSED_OPTION://Si cierras la ventana anterior muestra este mensaje.
                                    JOptionPane.showMessageDialog(this, "Búsqueda finalizada.");//Mensaje informativo.
                                    salir=true;
                                    break;
                        }
                    }while(!salir);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ese cliente no tiene más ventas.", "ERROR.", JOptionPane.ERROR_MESSAGE);//Mensaje informativo.
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Ese cliente no tiene ventas.", "ERROR.", JOptionPane.ERROR_MESSAGE);//Mensaje informativo.
            }
        }
    }

    //Método en el que mira si hay más ventas con el mismo Nombre
    private boolean masVentas(String nombre) {
        int cont=0;
        for(int i=0; i< ventas.size();i++){
            if(ventas.get(i).getCliente().equals(nombre)){
                cont++;
                if(cont>1){
                    return true;
                }
            }
        }
        return false;
    }
    
    //Validar Nombre
    private static boolean validarNombre(String nombre){
        String patron = "[a-zA-ZñÑáéíóúÁÉÍÓÚ\\s]{1,15}";
        return nombre.matches(patron);
    }
}
