/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formulario;

import static formulario.Formulario.calcularLetraDni;
import static formulario.Formulario.dniCorrecto;
import static formulario.Formulario.validarCodPostal;
import static formulario.Formulario.validarCodigo;
import static formulario.Formulario.validarDomicilio;
import static formulario.Formulario.validarEmail;
import static formulario.Formulario.validarNombre;
import static formulario.Formulario.validarTelFaxMov;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Frans
 */
public class JFormFormulario extends javax.swing.JFrame {

    /**
     * Creates new form JFormFormulario
     */
    public JFormFormulario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTextFieldLetraNif = new javax.swing.JTextField();
        jLabelApellidos = new javax.swing.JLabel();
        jLabelDomicilio = new javax.swing.JLabel();
        jLabelCp = new javax.swing.JLabel();
        jLabelLocalidad = new javax.swing.JLabel();
        jLabelTelf = new javax.swing.JLabel();
        jLabelMovil = new javax.swing.JLabel();
        jLabelFax = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jTextFieldTotal = new javax.swing.JTextField();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jTextFieldNif = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldDomicilio = new javax.swing.JTextField();
        jTextFieldCp = new javax.swing.JTextField();
        jTextFieldLocalidad = new javax.swing.JTextField();
        jTextFieldTelf = new javax.swing.JTextField();
        jTextFieldMovil = new javax.swing.JTextField();
        jTextFieldFax = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldCod = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Prueba de entrada de datos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("N.I.F.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jTextFieldLetraNif.setEditable(false);
        getContentPane().add(jTextFieldLetraNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 30, -1));

        jLabelApellidos.setText("Apellidos");
        getContentPane().add(jLabelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabelDomicilio.setText("Domicilio");
        getContentPane().add(jLabelDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jLabelCp.setText("C.P.");
        getContentPane().add(jLabelCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabelLocalidad.setText("Localidad");
        getContentPane().add(jLabelLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        jLabelTelf.setText("Teléfono");
        getContentPane().add(jLabelTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabelMovil.setText("Móvil");
        getContentPane().add(jLabelMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabelFax.setText("Fax");
        getContentPane().add(jLabelFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabelEmail.setText("e-mail");
        getContentPane().add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabelTotal.setText("Total");
        getContentPane().add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));

        jTextFieldTotal.setEditable(false);
        jTextFieldTotal.setText("0");
        getContentPane().add(jTextFieldTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 90, -1));

        jButtonAceptar.setText("Aceptar");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, -1, -1));

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 320, -1, -1));

        jTextFieldNif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNifKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNif, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 80, -1));

        jTextFieldNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldNombreKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 220, -1));

        jTextFieldApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldApellidosKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 410, 30));

        jTextFieldDomicilio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDomicilioKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldDomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 440, -1));

        jTextFieldCp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCpKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldCp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, -1));

        jTextFieldLocalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLocalidadKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 280, -1));

        jTextFieldTelf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldTelfKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldTelf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, -1));

        jTextFieldMovil.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldMovilKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldMovil, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 100, -1));

        jTextFieldFax.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFaxKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldFax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 100, -1));

        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 320, -1));

        jTextFieldCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodFocusLost(evt);
            }
        });
        jTextFieldCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodKeyPressed(evt);
            }
        });
        getContentPane().add(jTextFieldCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        confirmarFormulario();
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        resetFields();
        jTextFieldCod.grabFocus();
    }//GEN-LAST:event_jButtonCancelarActionPerformed
//Begin KeyEvent.VK_ENTER. On ENTER press, it shall focus the next field.
    private void jTextFieldCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNif.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldCodKeyPressed

    private void jTextFieldNifKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNifKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldNombre.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldNifKeyPressed

    private void jTextFieldNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldNombreKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldApellidos.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldNombreKeyPressed

    private void jTextFieldApellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldApellidosKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldDomicilio.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldApellidosKeyPressed

    private void jTextFieldDomicilioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDomicilioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldCp.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldDomicilioKeyPressed

    private void jTextFieldCpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCpKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldLocalidad.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldCpKeyPressed

    private void jTextFieldLocalidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLocalidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldTelf.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldLocalidadKeyPressed

    private void jTextFieldTelfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldTelfKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldMovil.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldTelfKeyPressed

    private void jTextFieldMovilKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldMovilKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldFax.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldMovilKeyPressed

    private void jTextFieldFaxKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFaxKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jTextFieldEmail.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldFaxKeyPressed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jButtonAceptar.grabFocus();
	}
    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodFocusLost
        //on loss of focus for field Codigo add 0's on the left
		String show = "";
		for (int i = 0; i < 6 - jTextFieldCod.getText().length(); i++) {
			show += "0";
		}
		show += jTextFieldCod.getText();
		jTextFieldCod.setText(show);
    }//GEN-LAST:event_jTextFieldCodFocusLost
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormFormulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFormFormulario().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelApellidos;
    private javax.swing.JLabel jLabelCp;
    private javax.swing.JLabel jLabelDomicilio;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFax;
    private javax.swing.JLabel jLabelLocalidad;
    private javax.swing.JLabel jLabelMovil;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTelf;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldCp;
    private javax.swing.JTextField jTextFieldDomicilio;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFax;
    private javax.swing.JTextField jTextFieldLetraNif;
    private javax.swing.JTextField jTextFieldLocalidad;
    private javax.swing.JTextField jTextFieldMovil;
    private javax.swing.JTextField jTextFieldNif;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTelf;
    private javax.swing.JTextField jTextFieldTotal;
    // End of variables declaration//GEN-END:variables
    
    //Validaciones
    private void confirmarFormulario() {
       String cod = jTextFieldCod.getText();
       String dni = jTextFieldNif.getText();
       String nombre = jTextFieldNombre.getText();
       String apellido = jTextFieldApellidos.getText();
       String domicilio = jTextFieldDomicilio.getText();
       String cp = jTextFieldCp.getText();
       String localidad = jTextFieldLocalidad.getText();
       String telefono = jTextFieldTelf.getText();
       String movil = jTextFieldMovil.getText();
       String fax = jTextFieldFax.getText();
       String email = jTextFieldEmail.getText();
       
     
       
       //Validar Código
       if(validarCodigo(cod)){
          
           //Validar NIF
            if(dniCorrecto(dni)){
               char letra = calcularLetraDni(dni);
               jTextFieldLetraNif.setText(String.valueOf(letra));
               //Validar Nombre
                if(validarNombre(nombre)){
                    //Validar Apellidos
                           if(validarNombre(apellido)){
                                //Validar Domicilio
                                if(validarDomicilio(domicilio)){
                                    //Validar CP
                                    if(validarCodPostal(cp)){
                                       //Validar Localidad
                                        if(validarNombre(localidad)){
                                             //Validar Teléfono
                                             if(validarTelFaxMov(telefono)){
                                                  //Validar Móvil
                                                  if(validarTelFaxMov(movil)){
                                                      //Validar Fax
                                                       if(validarTelFaxMov(fax)){
                                                            //Validar Email
                                                            if(validarEmail(email)){
                                                                JOptionPane.showMessageDialog(this, "Datos correctos", "Todos los datos introducidos son correctos", JOptionPane.YES_NO_CANCEL_OPTION);
                                                                resetFields();
                                                                jTextFieldCod.grabFocus();
                                                            }else{
                                                                JOptionPane.showConfirmDialog(this,"El Email es incorrecto",
                                                                                 "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                                                jTextFieldEmail.grabFocus();
                                                            }
                                                       }else{
                                                           JOptionPane.showConfirmDialog(this,"La Localidad debe tener 9 dígitos",
                                                                            "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                                           jTextFieldFax.grabFocus();
                                                       }
                                                  }else{
                                                      JOptionPane.showConfirmDialog(this,"El Móvil debe tener 9 dígitos",
                                                                       "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                                      jTextFieldMovil.grabFocus();
                                                  } 
                                             }else{
                                                 JOptionPane.showConfirmDialog(this,"El teléfono debe tener 9 dígitos",
                                                                  "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                                 jTextFieldTelf.grabFocus();
                                             }
                                        }else{
                                            JOptionPane.showConfirmDialog(this,"La Localidad debe tener un máximo de 15 carácteres",
                                                             "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                            jTextFieldLocalidad.grabFocus();
                                        }
                                    }else{
                                        JOptionPane.showConfirmDialog(this,"El Código Postal necesita 5 dígitos",
                                                     "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                        jTextFieldCp.grabFocus();
                                    }
                                }else{
                                    JOptionPane.showConfirmDialog(this,"El Domicilio es incorrecto",
                                                     "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                                    jTextFieldDomicilio.grabFocus();
                                }
                           }else{
                               JOptionPane.showConfirmDialog(this,"El Apellido debe tener un máximo de 15 carácteres",
                                                "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                               jTextFieldApellidos.grabFocus();
                           }
                }else{
                    JOptionPane.showConfirmDialog(this,"El Nombre debe tener un máximo de 15 carácteres",
                                     "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                    jTextFieldNombre.grabFocus();
                }
            
            }else{
                JOptionPane.showConfirmDialog(this,"El NIF debe tener 8 números",
                                 "Gestión de clientes", JOptionPane.CLOSED_OPTION);
                jTextFieldNif.grabFocus();
            }
       }else{
           JOptionPane.showConfirmDialog(this,"El Código debe tener un máximo de 6 carácteres",
                            "Gestión de clientes", JOptionPane.CLOSED_OPTION);
           jTextFieldCod.grabFocus();
       }    
    }
    //Vacío de campos y reset del color de las celdas
    private void resetFields() {
        jTextFieldCod.setText(null);
        jTextFieldNif.setText(null);
        jTextFieldLetraNif.setText(null);
        jTextFieldNombre.setText(null);
        jTextFieldApellidos.setText(null);
        jTextFieldDomicilio.setText(null);
        jTextFieldCp.setText(null);
        jTextFieldLocalidad.setText(null);
        jTextFieldTelf.setText(null);
        jTextFieldEmail.setText(null);
        jTextFieldMovil.setText(null);
        jTextFieldFax.setText(null);  
    }

   

}
